# Practical Lab: Week 3

Note: This practical session is based on the exercises in section 2.4 (Applied) of the module's book.

## Part I: The college dataset

1. Import `Pandas`
2. From the Moodle page (week 3, lab) get the `College.csv` CSV file and put it in the same folder where you saved your Jupyter notebook
3. Read the CSV file as a variable called `college`
4. Inspect the contents of the dataframe by using the `head()` method from `Pandas`

In [ ]:
# Importar biblioteca pandas
import pandas as pd
# Importar dataframe
college = pd.read_csv('College.csv')
# Dataframe es una representaci√≥n rectangular de datos
college.head()

,Unnamed: 0,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
0,Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
1,Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
2,Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
3,Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
4,Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

6. Is this a _rectangular_ data structure? If so, What entities are represented in the rows?

In [ ]:
# Si. Las entidades son college americanos

The column variables refer to the following information:

- **Private** : Public/private indicator
- **Apps** : Number of applications received
- **Accept** : Number of applicants accepted
- **Enroll** : Number of new students enrolled
- **Top10perc** : New students from top 10 % of high school class
- **Top25perc** : New students from top 25 % of high school class
- **F.Undergrad** : Number of full-time undergraduates
- **P.Undergrad** : Number of part-time undergraduates
- **Outstate** : Out-of-state tuition
- **Room.Board** : Room and board costs
- **Books** : Estimated book costs
- **Personal** : Estimated personal spending
- **PhD** : Percent of faculty with Ph.D.s
- **bold text**Terminal : Percent of faculty with terminal degree
- **S.F.Ratio** : Student/faculty ratio
- **perc.alumni** : Percent of alumni who donate
- **Expend** : Instructional expenditure per student
- **Grad.Rate** : Graduation rate

7. Use the `describe()` method on the `college` dataframe. Spend some time trying to figure out what information is provided. check the documentation [here.](https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.describe.html)

In [ ]:
#Todas las columnas num√©ricas las va a ordenar y va a calcular todos los datos
college.describe()

,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
count,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.000000,777.00000
mean,3001.638353,2018.804376,779.972973,27.558559,55.796654,3699.907336,855.298584,10440.669241,4357.526384,549.380952,1340.642214,72.660232,79.702703,14.089704,22.743887,9660.171171,65.46332
std,3870.201484,2451.113971,929.176190,17.640364,19.804778,4850.420531,1522.431887,4023.016484,1096.696416,165.105360,677.071454,16.328155,14.722359,3.958349,12.391801,5221.768440,17.17771
min,81.000000,72.000000,35.000000,1.000000,9.000000,139.000000,1.000000,2340.000000,1780.000000,96.000000,250.000000,8.000000,24.000000,2.500000,0.000000,3186.000000,10.00000
25%,776.000000,604.000000,242.000000,15.000000,41.000000,992.000000,95.000000,7320.000000,3597.000000,470.000000,850.000000,62.000000,71.000000,11.500000,13.000000,6751.000000,53.00000
50%,1558.000000,1110.000000,434.000000,23.000000,54.000000,1707.000000,353.000000,9990.000000,4200.000000,500.000000,1200.000000,75.000000,82.000000,13.600000,21.000000,8377.000000,65.00000
75%,3624.000000,2424.000000,902.000000,35.000000,69.000000,4005.000000,967.000000,12925.000000,5050.000000,600.000000,1700.000000,85.000000,92.000000,16.500000,31.000000,10830.000000,78.00000
max,48094.000000,26330.000000,6392.000000,96.000000,100.000000,31643.000000,21836.000000,21700.000000,8124.000000,2340.000000,6800.000000,103.000000,100.000000,39.800000,64.000000,56233.000000,118.00000

8. Notice we have the `college` dataframe indexed by column index, and the column with the university names has no name itself, we want to index by the universities. Play with the `Pandas` methods `rename` and `set_index` so that you (a) get rid of the numerical index, (b) make the universities column become the new index, and call that column `College`

In [ ]:
# Indicar para Pandas el nombre correcto de la columna
college = college.rename({'Unnamed: 0': 'College' }, axis=1) # Axis 1 = Columnas | Axis 0 = Filas
# Indicar qu√© columna pasa a ser el index
college = college.set_index('College')

KeyError: "None of ['College'] are in the columns"

In [ ]:
college.head()

,Private,Apps,Accept,Enroll,Top10perc,Top25perc,F.Undergrad,P.Undergrad,Outstate,Room.Board,Books,Personal,PhD,Terminal,S.F.Ratio,perc.alumni,Expend,Grad.Rate
College,,,,,,,,,,,,,,,,,,
Abilene Christian University,Yes,1660,1232,721,23,52,2885,537,7440,3300,450,2200,70,78,18.1,12,7041,60
Adelphi University,Yes,2186,1924,512,16,29,2683,1227,12280,6450,750,1500,29,30,12.2,16,10527,56
Adrian College,Yes,1428,1097,336,22,50,1036,99,11250,3750,400,1165,53,66,12.9,30,8735,54
Agnes Scott College,Yes,417,349,137,60,89,510,63,12960,5450,450,875,92,97,7.7,37,19016,59
Alaska Pacific University,Yes,193,146,55,16,44,249,869,7560,4120,800,1500,76,72,11.9,2,10922,15

9. Use the `pd.plotting.scatter_matrix()` function to produce a scatterplot matrix of the first columns `[Top10perc, Apps, Enroll]`.

For this, you need to slice your dataframe on the three columns. Recall that you can reference a list C of columns of a data frame `A`  using  `A[C]` .

10. Use the `boxplot()` method of college to produce side-by-side boxplots of `Outstate` versus `Private`.

11. Create a new qualitative variable, called `Elite`, by *binning* the `Top10perc` variable into two groups based on whether or not the proportion of students coming from the top 10% of their high school classes exceeds 50%.

In [ ]:
# Se puede hacer describe() de una columna
college['Top10perc'].describe()

Use the `value_counts()` method of college`['Elite']` to see how many elite universities there are. Finally, use the `boxplot()` method again to produce side-by-side boxplots of `Outstate` versus `Elite`.

In [ ]:
# Nueva
college['Elite'] = pd.cut(college['Top10perc'], [0, 50, 100],
labels=['No', 'Yes'])
# Print normal
college

12. Use the `plot.hist()` method of `college` to produce some histograms with differing numbers of bins for a few of the quantitative variables. The command `plt.subplots(2, 2)` may be useful: it will divide the plot window into four regions so that four plots can be made simultaneously. By changing the arguments you can divide the screen up in other combinations.

In [ ]:
import matplotlib.pyplot as plt
n = 2
figs, axs = plt.subplots(n, n)

13. Continue exploring the data, and provide a brief summary of what you discover.

## Part II: The Auto dataset

1. Import `Pandas`
2. From the Moodle page (week 3, lab) get the `Auto.csv` CSV file and put it in the same folder where you saved your Jupyter notebook
3. Read the CSV file as a variable called `Auto`
4. Inspect the contents of the dataframe by using the `head()` method from `Pandas`

In [40]:
import pandas as pd
Auto = pd.read_csv('Auto.csv')
Auto.head()

,mpg,cylinders,displacement,horsepower,weight,acceleration,year,origin,name
0,18.0,8,307.0,130,3504,12.0,70,1,chevrolet chevelle malibu
1,15.0,8,350.0,165,3693,11.5,70,1,buick skylark 320
2,18.0,8,318.0,150,3436,11.0,70,1,plymouth satellite
3,16.0,8,304.0,150,3433,12.0,70,1,amc rebel sst
4,17.0,8,302.0,140,3449,10.5,70,1,ford torino

5. Which of the predictors are quantitative, and which are qualitative?

In [ ]:
"""
Todas son cuantitativas. Excepto el nombre.
"""

6. What is the range of each quantitative predictor? You can answer this using the `min()` and `max()` methods in numpy.

In [11]:
Auto.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 397 entries, 0 to 396
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   mpg           397 non-null    float64
 1   cylinders     397 non-null    int64
 2   displacement  397 non-null    float64
 3   horsepower    397 non-null    object
 4   weight        397 non-null    int64
 5   acceleration  397 non-null    float64
 6   year          397 non-null    int64
 7   origin        397 non-null    int64
 8   name          397 non-null    object
dtypes: float64(3), int64(4), object(2)
memory usage: 28.0+ KB

In [28]:
Auto.describe()
# Horsepower es un n√∫mero, pero aqu√≠ figura como un objecto
Auto['horsepower'].head()
len(Auto)
print(Auto['horsepower'].unique())
# Una interrogaci√≥n est√° haciendo que todos los valores se conviertan en string

['130' '165' '150' '140' '198' '220' '215' '225' '190' '170' '160' '95'
 '97' '85' '88' '46' '87' '90' '113' '200' '210' '193' 100 '100' '105'
 '175' '153' '180' '110' '72' '86' '70' '76' '65' '69' '60' '80' '54'
 '208' '155' '112' '92' '145' '137' '158' '167' '94' '107' '230' '49' '75'
 '91' '122' '67' '83' '78' '52' '61' '93' '148' '129' '96' '71' '98' '115'
 '53' '81' '79' '120' '152' '102' '108' '68' '58' '149' '89' '63' '48'
 '66' '139' '103' '125' '133' '138' '135' '142' '77' '62' '132' '84' '64'
 '74' '116' '82']

In [41]:
# Hay que eliminar la interrogaci√≥n
interrogation = Auto[Auto['horsepower'].isin(['?'])]

"""
for id, x in enumerate(Auto['horsepower']):
  if not x.isnumeric():
    print(id,x)
"""
print(interrogation)

# Una opci√≥n es cambiar los valores (32, 126, 330, 336, 354)

Auto.loc[32, 'horsepower'] = 100
Auto.loc[126, 'horsepower'] = 100
Auto.loc[330, 'horsepower'] = 100
Auto.loc[336, 'horsepower'] = 100
Auto.loc[354, 'horsepower'] = 100

# Otra opci√≥n es dropear esos datos y resetear el index (porque no son significativos en esa cantidad)
"""
Auto = Auto.drop(Auto.index[32]).reset_index(drop=True)
"""

      mpg  cylinders  displacement horsepower  weight  acceleration  year  \
32   25.0          4          98.0          ?    2046          19.0    71
126  21.0          6         200.0          ?    2875          17.0    74
330  40.9          4          85.0          ?    1835          17.3    80
336  23.6          4         140.0          ?    2905          14.3    80
354  34.5          4         100.0          ?    2320          15.8    81

     origin                  name
32        1            ford pinto
126       1         ford maverick
330       2  renault lecar deluxe
336       1    ford mustang cobra
354       2           renault 18i

'\nAuto = Auto.drop(Auto.index[32]).reset_index(drop=True)\n'

8. What is the mean and standard deviation of each quantitative predictor?

In [42]:
# Convert 'horsepower' column to numeric, coercing errors to NaN
Auto['horsepower'] = pd.to_numeric(Auto['horsepower'], errors='coerce')

print(Auto['mpg'].mean())
print(Auto['cylinders'].mean())
print(Auto['displacement'].mean())
print(Auto['horsepower'].mean())
print(Auto['weight'].mean())
print(Auto['acceleration'].mean())
print(Auto['year'].mean())
print(Auto['origin'].mean())

23.51586901763224
5.458438287153652
193.53274559193954
104.41309823677582
2970.2619647355164
15.55566750629723
75.99496221662469
1.5743073047858942

In [37]:
print(Auto['mpg'].std())
print(Auto['cylinders'].std())
print(Auto['displacement'].std())
print(Auto['horsepower'].std())
print(Auto['weight'].std())
print(Auto['acceleration'].std())
print(Auto['year'].std())
print(Auto['origin'].std())

7.825803928946562
1.7015769807918517
104.37958329992945
38.25064374876413
847.9041194897246
2.7499952929761515
3.690004901461673
0.8025494957970386

9. Now remove the 10th through 85th observations. What is the range, mean, and standard deviation of each predictor in the subset of the data that remains?

In [38]:
Auto = Auto.drop(Auto.index[9:85])

In [44]:
# Hacerlo en un for es mucho m√°s elegante
for pred in list(Auto)[:-1]:
  print(f"{pred}: mean={np.mean(Auto[pred])}, std={np.std(Auto[pred])}")

mpg: mean=23.51586901763224, std=7.815941538224255
cylinders: mean=5.458438287153652, std=1.699432585509141
displacement: mean=193.53274559193954, std=104.24803997948825
horsepower: mean=104.41309823677582, std=38.20243875954447
weight: mean=2970.2619647355164, std=846.8355568478047
acceleration: mean=15.55566750629723, std=2.746529639056109
year: mean=75.99496221662469, std=3.6853546098832153
origin: mean=1.5743073047858942, std=0.8015380908636408

10. Using the full data set, investigate the predictors graphically, using scatterplots or other tools of your choice. Create some plots highlighting the relationships among the predictors. Comment on your findings.

In [ ]:
# prompt: Using the full data set, investigate the predictors graphically, using scatterplots or other tools of your choice. Create some plots highlighting the relationships among the predictors. Comment on your findings

import pandas as pd
import matplotlib.pyplot as plt

# Assuming 'Auto' dataframe is already loaded and processed

# Scatterplot matrix for selected variables
pd.plotting.scatter_matrix(Auto[['mpg', 'horsepower', 'weight']], figsize=(10, 10))
plt.show()


# Scatterplot of mpg vs horsepower
plt.scatter(Auto['horsepower'], Auto['mpg'])
plt.xlabel('Horsepower')
plt.ylabel('MPG')
plt.title('Relationship between Horsepower and MPG')
plt.show()

# Scatterplot of weight vs mpg
plt.scatter(Auto['weight'], Auto['mpg'])
plt.xlabel('Weight')
plt.ylabel('MPG')
plt.title('Relationship between Weight and MPG')
plt.show()

# Boxplot of mpg by origin
Auto.boxplot(column='mpg', by='origin')
plt.title('MPG Distribution by Origin')
plt.show()

# Histogram of mpg
plt.hist(Auto['mpg'], bins=10)
plt.xlabel('MPG')
plt.ylabel('Frequency')
plt.title('Distribution of MPG')
plt.show()

# You can explore other relationships and create more plots as needed.

# Comments on findings (replace with your own observations):
# From the scatterplot matrix, we can observe the relationships between mpg, horsepower, and weight.
# For example, we see a negative correlation between horsepower and mpg, which means that as horsepower increases, mpg tends to decrease.
# Similarly, there is a negative correlation between weight and mpg.
# The boxplot of mpg by origin shows that cars from different origins have different mpg distributions.
# The histogram of mpg shows the distribution of mpg values in the dataset.

11. Suppose that we wish to predict gas mileage (mpg) on the basis of the other variables. Do your plots suggest that any of the other variables might be useful in predicting mpg? Justify your answer.

## Part III: The Boston dataset

1. Import `Pandas`
2. From ISLP library get Boston dataset. (Info [link text](https://islp.readthedocs.io/en/latest/datasets/Boston.html))
4. Inspect the contents of the dataframe by using the `head()` method from `Pandas`

In [ ]:
!pip install --force-reinstall -v "numpy==1.22"

In [ ]:
!pip install ISLP

In [ ]:
from ISLP import load_data

Boston = load_data('Boston')
Boston.columns

Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'lstat', 'medv'],
      dtype='object')

1. How many rows are in this data set? How many columns? What do the rows and columns represent?

4. Make some pairwise scatterplots of the predictors (columns) in this data set. Describe your findings.

5. Are any of the predictors associated with per capita crime rate? If so, explain the relationship.

6. Do any of the suburbs of Boston appear to have particularly high crime rates? Tax rates? Pupil-teacher ratios? Comment on the range of each predictor.

7. How many of the suburbs in this data set bound the Charles river?

8. What is the median pupil-teacher ratio among the towns in this data set?

9. Which suburb of Boston has lowest median value of owner- occupied homes? What are the values of the other predictors for that suburb, and how do those values compare to the overall ranges for those predictors? Comment on your findings.

10. In this data set, how many of the suburbs average more than seven rooms per dwelling? More than eight rooms per dwelling? Comment on the suburbs that average more than eight rooms per dwelling.